### ISSUE TITLE
Concurrency Issues

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ABY#69]
This issue tracks concurrency related problems that are currently known.

- [x] abyparty/-setup: add synchronization to worker job (fixed in #67 )
- [x] more fixes in encryptogroup/ENCRYPTO_utils#6
- [ ] Check the current state of #16
- [ ] After a channel is destroyed the RcvThread tries to signal its condition variable.
- [ ] There is probably an issues where `ABYParty::ThreadSendValues`/`ThreadReceiveValues` access a buffer concurrently with other methods from different sharing schemes.
- [ ] ...

**Comment by sebastianst** [comment]
Probably related: If ABY is part of a multi-threaded application, it may refuse to execute the circuit and dies with the error `A listener has already been registered on channel 0`. This comes from an OT receiver thread. Stacktrace:
```
#0  RcvThread::add_listener (this=0x7fffe800d040, channelid=0x0, rcv_event=0x7fff74000b70, fin_event=0x7fff74000be0) at .../extern/ABY/extern/ENCRYPTO_utils/src/ENCRYPTO_utils/rcvthread.cpp:66
#1  0x0000555555d47d04 in channel::channel (this=0x7fff74000b20, channelid=0x0, rcver=0x7fffe800d040, snder=0x7fffe8002300) at .../extern/ABY/extern/ENCRYPTO_utils/src/ENCRYPTO_utils/channel.cpp:14
#2  0x0000555555d3b1af in IKNPOTExtRec::receiver_routine (this=0x7fffe806b7d0, id=0x0, myNumOTs=0x28b29) at .../extern/ABY/extern/OTExtension/ot/iknp-ot-ext-rec.cpp:25
#3  0x0000555555d40bf2 in OTExtRec::OTReceiverThread::ThreadMain (this=0x7fffac004ef0) at .../extern/ABY/extern/OTExtension/ot/ot-ext-rec.h:80
#4  0x0000555555d58f0d in CThread::<lambda()>::operator()(void) const (__closure=0x7fffac000c28) at .../extern/ABY/extern/ENCRYPTO_utils/src/ENCRYPTO_utils/thread.cpp:14
#5  0x0000555555d594df in std::__invoke_impl<void, CThread::Start()::<lambda()> >(std::__invoke_other, CThread::<lambda()> &&) (__f=...) at /usr/include/c++/8.2.1/bits/invoke.h:60
#6  0x0000555555d592ed in std::__invoke<CThread::Start()::<lambda()> >(CThread::<lambda()> &&) (__fn=...) at /usr/include/c++/8.2.1/bits/invoke.h:95
#7  0x0000555555d59700 in std::thread::_Invoker<std::tuple<CThread::Start()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x7fffac000c28) at /usr/include/c++/8.2.1/thread:244
#8  0x0000555555d596d6 in std::thread::_Invoker<std::tuple<CThread::Start()::<lambda()> > >::operator()(void) (this=0x7fffac000c28) at /usr/include/c++/8.2.1/thread:253
#9  0x0000555555d596ba in std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Start()::<lambda()> > > >::_M_run(void) (this=0x7fffac000c20) at /usr/include/c++/8.2.1/thread:196
#10 0x00007ffff7490063 in execute_native_thread_routine () at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#11 0x00007ffff7c86a9d in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007ffff716ca43 in clone () from /usr/lib/libc.so.6
```
So somehow the receive threads gets passed a listener that is already marked as in use by another thread.
This currently **renders ABY unusable** on two of my machines when it is used as part of a multi-threading application. Strangely, at @TKussel 's box, it is still working.

If I instantiate and execute the `ABYParty` as part of a single-threaded application in `main()`, I don't have this problem so it must be related to some race-condition in the network threads that only surfaces if ABY is part of a larger multi-threaded application.

**Comment by lenerd** [comment]
This issue also appears during the abytest in case it gets to the AES part.

I have an idea: 
I guess the problem is that the `std::array<...> RcvThread::listeners` is not zeroed on construction of a new `RcvThread`. Hence, sometimes the `inuse` flag is true for a new instance.

@sebastianst Would you try [this branch for ENCRYPTO_utils](https://github.com/lenerd/ENCRYPTO_utils/tree/lenerd/fix-rcvthread) and tell me if the issue still occurs?

**Comment by sebastianst** [comment]
@lenerd AWESOME that fixed it! please merge upstream and update ABY's submodule. Thanks :)

**Comment by lenerd** [comment]
@sebastianst Done.
